#! /usr/bin/env ruby

main_branch = `git symbolic-ref --short HEAD`.strip
`git stash`
`git fetch`
`git checkout #{main_branch}`
`git pull`
branches = `git branch`.split("\n") - ["* #{main_branch}"]

branches.each do |b|
  `git checkout #{b}`
  merge_output = `git merge #{main_branch}`
  if merge_output.match(/^CONFLICT/)
    `git reset --hard`
  end
  diff_output = `git diff #{main_branch}`
  `git checkout #{main_branch}`
  if diff_output.empty?
    `git branch -D #{b}`
  end
end
